# Pandas Basic

## Understanding Series and DataFrames

Pandas is a Python library that provides powerful tools for data analysis and manipulation. It has two main data structures:

- Series
- DataFrames

Think of them as containers to store data in an organized way. For beginners, it's helpful to think of a Series as a column of data, and a DataFrame as a whole table with rows and columns.

### What is Pandas Series?

A Series is a one-dimensional array, like a single column of data in a spreadsheet. Each element in a Series has an index (like a label) that makes it easy to find specific values.

Key Points about Series: **One-dimensional**: A Series only has one column of data, so it's simpler than a DataFrame.

**Indexed**: Each value has an index label, so you can access values by their label.

**Holds one data type**: All values in a Series are usually of the same data type (e.g., all integers, all floats, or all strings).

**When to Use Series:**

- When you need to store a single column or list of data.
- For simpler datasets where you only need one type of information, like a list of ages or prices.

In [1]:
import pandas as pd

print(pd.__version__)

3.0.3

#### Creating a Series in Pandas:

To create a Series, we can use the pd.Series() function. Let's look at different ways to create a Series.

*Example 1: Creating a Series from a List*

In [2]:
# Creating a series from a list of numbers

data = [10,20,30,40]
series = pd.Series(data)

print("Series with default index:\n", series)

Series with default index:
 0    10
1    20
2    30
3    40
dtype: int64

Explanation:

> We used a list `[10, 20, 30, 40]` to create the Series.
> 
> Pandas automatically assigns default indices (0, 1, 2, 3).

*Example 2: Creating with a Custom index*

You can also assign custom labels (or indices) to each element in a Series

In [3]:
# Creating a Series with custom index Labels
labels = ['a', 'b', 'c', 'd']
series = pd.Series(data, index=labels)
print("Series with custom indices:\n", series)

Series with custom indices:
 a    10
b    20
c    30
d    40
dtype: int64

Explanation:

> The list `['a', 'b', 'c', 'd']` specifies custom labels for the Series.

#### Accessing values in a Series

You can retrieve specific values by using their index labels.

In [4]:
print("Value at index 'b': ", series['b'])

Value at index 'b':  20

### What is Pandas DataFrame?

A DataFrame is a two-dimensional data structure, like a table, where data is organized in rows and columns. Each column can have a different data type (e.g., integers, floats, strings).

*Key Points about DataFrames*:

- Two-dimensional: A DataFrame has rows and columns, so it's like a table.
- Labeled rows and columns: Rows and columns both have labels, making it easy to access data.
- Multiple data types: Each column can store different types of data (e.g., numbers, text).

*When to Use DataFrames*:

- When you need to store data in a table format, with multiple columns representing different attributes.
- For more complex datasets where each column represents a different variable or feature.

#### Creating a DataFrame in Pandas

To create a DataFrame, you can use the pd.DataFrame () function with different types of data sources.

In [5]:
# Creating a DataFrame from a Dictionary

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
print("DataFrame example:\n")
df

DataFrame example:

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

*Explanation*:

> We used a dictionary where each key (e.g., Name, Age, City) represents a column name, and each value is a list of column values.

#### Syntax for Creating DataFrames from Different Sources:

- `CSV File`: `df = pd.read csv('file.csv')`: eads data from a CSV file.
- `Excel File`: `df= pd. read excel('file.xIsx')`: Reads data from an Excel file.
- `SQL Database`: `df = pd. read_sql(query, connection)`: Reads data from a database query.

## Essential Operations in Pandas

Now that we understand Series and DataFrames, let's explore some common operations for handling data in a DataFrame.

In [6]:
# Creating a DataFrame from a Dictionary

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

### Selecting, Filtering and Modifying Data

#### `Selecting Data`

You can retrieve specific rows, columns, or individual cells.

1. **Accessing a column**:

In [7]:
df['Name'] # Step 1: Access a single olumn using its name

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

2. **Accessing Multiple Columns**:

In [8]:
df[['Name', 'Age']]

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

3. ***Accessing Rows Using `iloc`, `loc`, `at` and `iat`***

In [9]:
# Creating a DataFrame from a Dictionary

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 50],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data, index=['a','b','c', 'd'])
df

      Name  Age         City
a    Alice   25     New York
b      Bob   30  Los Angeles
c  Charlie   35      Chicago
d    David   50      Houston

a. `loc`: ***Label Based Indexing***

- loc is used for label-based indexing.
- This means you can use the labels (index or column names) to access rows and columns.
- loc is inclusive of the end index, so it will include both the start and end of the specified range.
- Syntax:

`DataFrame.loc[row_label, column_label]`

- *Example: Using loc to Select Rows and Columns by Labels*

In [10]:
# Select a single row using label

row_a = df.loc['a']
print("Row 'a':\n", row_a)

Row 'a':
 Name       Alice
Age           25
City    New York
Name: a, dtype: object

In [11]:
# Select multiple rows and a specific column by labels

rows_bc_age_city = df.loc[['b', 'c'], ['Age', 'City']]
print("\nRows 'b' and 'c' with 'Age' and 'City' columns:\n", rows_bc_age_city)

Rows 'b' and 'c' with 'Age' and 'City' columns:
    Age         City
b   30  Los Angeles
c   35      Chicago

In [12]:
# Select Rows based on condition

age_above_30 = df.loc[df['Age']>30, 'Name']
print("\nNames of people older than 30:\n", age_above_30)

Names of people older than 30:
 c    Charlie
d      David
Name: Name, dtype: str

Explanation:

- `loc` : Access rows by index label.
- `df.loc['a']` : Selects all columns in row 'a' (Alice's details).
- `df.loc[['b', 'c'], ['Age', 'City' ]]` : Selects rows with labels 'b' and 'c', displaying only the 'Age' and 'City' columns.
- `df. loc[df[ 'Age'] › 30, 'Name ']` : Uses a condition to select rows where 'Age' is greater than 30, displaying only the 'Name' column.

**`loc` using slice methods**

In [13]:
df.loc['a':'b', 'Name':'Age']

    Name  Age
a  Alice   25
b    Bob   30

Here, we can see that index slicing can be done to get the vales.

But, one thing to notice, in normal slicing it would've been -> `[start_index:end_index+1]`,

but with `loc`, it is -> `[start_index:end_index]`

b. `iloc`: **Position Based Indexing**

- iloc is used for integer-location-based indexing.
- This means you specify row and column positions (0-based index) rather than labels
- iloc is also inclusive of the starting index but exclusive of the ending index (like Python slicing).
- Syntax:

DataFrame. iloc[row position, column_position]

- Example: Using iloc to Access Data by Position

In [14]:
# Creating a DataFrame from a Dictionary

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 50],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df = pd.DataFrame(data, index=['a','b','c', 'd'])
df

      Name  Age         City
a    Alice   25     New York
b      Bob   30  Los Angeles
c  Charlie   35      Chicago
d    David   50      Houston

In [15]:
# Select a single row by position
row_0 = df.iloc[0]
print ("Row 0: \n", row_0)

# Select multiple rows and specific columns by position
rows_1_2_columns_1_2 = df.iloc[1:3, 1:3]
print("\nRows 1 to 2, Columns 1 to 2: \n", rows_1_2_columns_1_2)

# Select a specific value by row and column position
value_row_2_col_1 = df. iloc[2, 1]
print("\nValue at Row 2, Column 1:", value_row_2_col_1)

Row 0:
 Name       Alice
Age           25
City    New York
Name: a, dtype: object

Rows 1 to 2, Columns 1 to 2:
    Age         City
b   30  Los Angeles
c   35      Chicago

Value at Row 2, Column 1: 35

*Explanation*:

- `df. iloc[0]` : Selects all columns in the first row (row 0).
- `df. iloc[1:3, 1:3]` : Selects rows 1 and 2 and columns 1 and 2, inclusive of the start but exclusive of the end.
- `df. iloc[2, 1]` : Retrieves the value in the third row (row index 2) and second column (column index 1).

Here, if you have noticed, we are using the regular `slice` expressions, which is, `[start_index:end_index+1]`

#### `Filtering` Techniques in Pandas

Filtering is crucial when working with data as it allows you to select rows that match specific conditions. Here's a comprehensive look at filtering techniques in Pandas, with examples to illustrate each approach.

In [16]:
# Sample Data

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 30, 35, 22, 28],
    'Salary': [50000, 54000, 61000, 45000, 52000]
}

df = pd.DataFrame(data)
df

      Name  Age  Salary
0    Alice   24   50000
1      Bob   30   54000
2  Charlie   35   61000
3    David   22   45000
4      Eva   28   52000

1. ***Boolean Indexing with Conditions***:

Boolean indexing lets you filter rows by applying conditions directly to columns. This technique is useful for straightforward conditional filters.

In [17]:
# Filter rows where Age > 25

df_age_above_25 = df[df['Age']>25]
print("\nRows with Age greater than 25:\n", df_age_above_25)

Rows with Age greater than 25:
       Name  Age  Salary
1      Bob   30   54000
2  Charlie   35   61000
4      Eva   28   52000

In [18]:
# Filter rows with multiple conditions: Age > 25 & Salary > 50000

df_multi_condition = df[(df['Age']>25) & (df['Salary']>50000)]
print("\nRows with Age greater than 25 and Salary greater than 60000:\n", df_multi_condition)

Rows with Age greater than 25 and Salary greater than 60000:
       Name  Age  Salary
1      Bob   30   54000
2  Charlie   35   61000
4      Eva   28   52000

Explanation:
- `df[df['Age'] > 25]` : Filters rows where the Age column is greater than 25.
- `df[ (df['Age"] > 25) & (df['Salary ] > 50000)]` :
  - Filters rows where Age is greater than 25 and Salary is more than 50,000.
  - The & operator is used to apply multiple conditions.

Here `and` functionality can be done using `&` and even `or` functionality can be done using `|`

2. ***Filtering Using isin0 for Multiple Values***:

The isin() method is ideal for filtering rows based on a set of specific values in a column.

In [19]:
# Filter Rows where Name is either 'Alice' or 'David'

df_names = df[df['Name'].isin(['Alice', 'David'])]
print("\nRows with name 'Alice' or 'David':\n", df_names)

Rows with name 'Alice' or 'David':
     Name  Age  Salary
0  Alice   24   50000
3  David   22   45000

In [20]:
# Filter rows where Age is either 24, 30 or 35

df_specific_ages = df[df['Age'].isin([24,30,35])]
print("\nRows with specific ages (24, 30 or 35):\n", df_specific_ages)

Rows with specific ages (24, 30 or 35):
       Name  Age  Salary
0    Alice   24   50000
1      Bob   30   54000
2  Charlie   35   61000

Explanation:
- `df[df[ Name']. isin(['Alice', 'David'|)]` :
  - Filters rows where the Name column contains either "Alice" or "David".
- `df[df[ Age'].isin([24, 30, 35])]` :
  - Filters rows where Age matches any value in `[24, 30, 35]`
  - This is useful for filtering specific sets of categorical or numeric values.

3. ***Filtering with isnull() or notnull() for Missing Data:***

Filtering based on missing data allows you to focus on rows with or without NaN values.

In [21]:
# Sample data with NaN values

data_with_nan = {
    'Name': ['Alice', 'Bob', 'Charlie',  None, 'Eva'],
    'Age': [24, None, 35, 22, None],
    'Salary': [50000, None, 61000, 45000, 52000]
}
df_nan = pd.DataFrame(data_with_nan)
df_nan

      Name   Age   Salary
0    Alice  24.0  50000.0
1      Bob   NaN      NaN
2  Charlie  35.0  61000.0
3      NaN  22.0  45000.0
4      Eva   NaN  52000.0

In [22]:
# Filter rows where Age is null

df_age_null = df_nan[df_nan['Age'].isnull()]
print("\nRows where Age is null:\n", df_age_null)

Rows where Age is null:
   Name  Age   Salary
1  Bob  NaN      NaN
4  Eva  NaN  52000.0

In [23]:
# Filter rows where Salary is not null

df_salary_not_null = df_nan[df_nan['Salary'].notnull()]
print("\nRows where Salary is not null:\n", df_salary_not_null)

Rows where Salary is not null:
       Name   Age   Salary
0    Alice  24.0  50000.0
2  Charlie  35.0  61000.0
3      NaN  22.0  45000.0
4      Eva   NaN  52000.0

*Explanation*:

- `df_nan[df_nan['Age'].isnull()]`:
  - Filters rows where **Age** column contains NaN values
  - `isnull()` is ideal for identifying missing data
- `df_nan[df_nan['Salary'].notnull()]`:
  - Filters rows where **Salary** column has non-null values
  - `notnull()` is helpful for selecting rows with comlpete data in a column

#### `Modifying Data`

You can add new columns or update values

In [24]:
# Creating a DataFrame with a Dictionary

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [25]:
df['Discount'] = df['Age'] * 2
df

      Name  Age         City  Discount
0    Alice   24     New York        48
1      Bob   27  Los Angeles        54
2  Charlie   22      Chicago        44

#### `Handling Missing Data`

- Missing data is common in real-world datasets. Pandas provides functions to identify and handle missing values

1. `Identifying Missing Data`:

   - Use `isna()` or `isnull`

In [26]:
import numpy as np

# Creating a DataFrame from a Dictionary

data = {
    'Name': ['Alice', 'Bob', np.nan],
    'Age': [24, 27, 22],
    'City': ['New York', np.nan, 'Chicago']
}
df = pd.DataFrame(data)
df.isna()

    Name    Age   City
0  False  False  False
1  False  False   True
2   True  False  False

*Explanation*:

> `df.isna()` returns a **DataFrame** of the same size as `df`, with `True` where data is missing and `False` where it's present

2. `Filling Missing Values (Imputation)`

   - When dealing with missing values you can replace NaN values `mean`, `median` and `mode` values of the column

In [27]:
# Creating a DataFrame from a Dictionary

df_with_nans = pd.DataFrame({'Score': [80, 90, None, 95, None]})
df_with_nans

   Score
0   80.0
1   90.0
2    NaN
3   95.0
4    NaN

In [28]:
# Fill Nans with mean

mean_inputed = df_with_nans['Score'].fillna(df_with_nans['Score'].mean())
print("Filled with Mean:\n", mean_inputed)

Filled with Mean:
 0    80.000000
1    90.000000
2    88.333333
3    95.000000
4    88.333333
Name: Score, dtype: float64

In [29]:
# Fill NaNs with median

median_inputed = df_with_nans['Score'].fillna(df_with_nans['Score'].median())
print("\nFilled with Median:\n", median_inputed)

Filled with Median:
 0    80.0
1    90.0
2    90.0
3    95.0
4    90.0
Name: Score, dtype: float64

In [30]:
# Filled with mode

mode_inputed = df_with_nans['Score'].fillna(df_with_nans['Score'].mode())
print("\nFilled with Mode:\n", mode_inputed)

Filled with Mode:
 0    80.0
1    90.0
2    95.0
3    95.0
4     NaN
Name: Score, dtype: float64

*Explanation*:

> - `fillna(df_with_nans['Score'].mean())`: Replaces missing values in Score with the column's mean
> - `fillna(df_with_nans['Score'].median())`: Replaces missing values in Score with the column's median
> - `fillna(df_with_nans['Score'].mode())`: Replaces missing values in Score with the column's mode

3. `Removing Rows/Columns with Missing Data`:

   - `dropna()`: Removes rows or columns with missing values

In [32]:
df.dropna(inplace=True)
df

    Name  Age      City
0  Alice   24  New York

*Explaination*:

> - `dropna()` removes rows that have at least one missing value.
> - `inplace=True` makes this change directly in df.

#### Data Transformation Techniques:

Pandas makes it easy to `sort`, `rename` and `modify`columns for better data clarity and usability

In [38]:
data = {
    'Name': ['Alice', 'Chuck', 'Hugo'],
    'Age': [28, 22, 24],
    'City': ['Newy York', 'Houston', 'Dallas']
}
df = pd.DataFrame(data, index=['c ','b','a'])
df

     Name  Age       City
c   Alice   28  Newy York
b   Chuck   22    Houston
a    Hugo   24     Dallas

1. **Sorting Data: `sort_values()` and `sort_index`**

In [39]:
# Sort Age in descending order

df_sorted_age = df.sort_values(by='Age', ascending=False)
df_sorted_age

     Name  Age       City
c   Alice   28  Newy York
a    Hugo   24     Dallas
b   Chuck   22    Houston

In [40]:
# Sort by index

df_sorted_index = df.sort_index()
df_sorted_index

     Name  Age       City
a    Hugo   24     Dallas
b   Chuck   22    Houston
c   Alice   28  Newy York

2. **`Renamiming Columns`: Rename columns for clarity**

In [41]:
df.rename(columns={'Name':'Person Name'}, inplace=True)
df

   Person Name  Age       City
c        Alice   28  Newy York
b        Chuck   22    Houston
a         Hugo   24     Dallas